"""
agents/writer.py
================
Writer Agent — ResearchOps Multi-Agent Pipeline

The final specialist in the pipeline. It receives all previous agent outputs
and synthesises them into a polished, structured markdown report saved to disk.

Key concepts demonstrated:
- Synthesis agent pattern: combines all upstream context into a final deliverable
- File I/O: saves the report as a .md file to the output/ folder
- Mock mode for cost-free development and testing
"""

from dotenv import load_dotenv
load_dotenv()

import anthropic
import os
from datetime import datetime

# Initialise the Anthropic client. API key is picked up automatically
# from the ANTHROPIC_API_KEY environment variable set in .env
client = anthropic.Anthropic()

# ---------------------------------------------------------------------------
# Mock Mode
# ---------------------------------------------------------------------------
# Set MOCK_MODE = True during development to avoid API costs.
#
# HOW TO SWITCH:
#   Development  → MOCK_MODE = True   (free, instant, no API calls)
#   Real testing → MOCK_MODE = False  (uses API credits, real writing)
# ---------------------------------------------------------------------------

MOCK_MODE = True

# ---------------------------------------------------------------------------
# System Prompt
# ---------------------------------------------------------------------------

WRITER_SYSTEM_PROMPT = """You are a professional research writer. You receive research,
analysis, and critique from a team of specialists and synthesise it into a single
polished markdown report.

Your report must follow this exact structure:
# [Topic] — Research Report
## Executive Summary
## Key Findings
## Analysis
## Critical Perspectives
## Conclusions
## Limitations

Rules:
- Write in clear, professional English
- Be balanced — incorporate both the analysis and the critique
- Use markdown formatting throughout
- The report should stand alone — a reader needs no other context"""


def run_writer(topic: str, research: str, analysis: str, critique: str) -> str:
    """
    Run the Writer Agent to produce the final markdown report.

    Receives all three upstream outputs (research, analysis, critique) and
    synthesises them into a structured markdown report, which is saved
    to the output/ folder as a .md file.

    This is the final stage of the pipeline. Its return value is the
    complete report text, and the side effect is a saved file.

    Args:
        topic (str): The original research topic from the CLI.
        research (str): Full output from the Researcher Agent.
        analysis (str): Full output from the Analyst Agent.
        critique (str): Full output from the Critic Agent.

    Returns:
        str: The full markdown report text.
    """

    print(f"\n[Writer] Writing final report on: {topic}")

    # ---------------------------------------------------------------------------
    # Mock Mode — returns fake report, no API call made
    # ---------------------------------------------------------------------------

    if MOCK_MODE:
        print("[Writer] MOCK MODE active — returning fake report (no API call)")
        report = f"""# {topic.title()} — Research Report

*Generated by ResearchOps Multi-Agent Pipeline*
*Date: {datetime.now().strftime("%Y-%m-%d %H:%M")}*

---

## Executive Summary

This report examines {topic} drawing on research, structured analysis, and 
critical review produced by a team of specialist AI agents. The findings suggest 
a field at an inflection point — significant momentum exists, but meaningful 
barriers to full realisation remain.

---

## Key Findings

- Adoption is accelerating, with year-on-year growth rates of approximately 40%
- 67% of organisations are actively piloting or deploying solutions
- Early adopters report cost reductions of up to 30%
- The market is projected to reach $45 billion by end of 2025
- Regulatory frameworks are lagging significantly behind deployment rates

---

## Analysis

The data points to a sector moving rapidly from experimentation to mainstream 
adoption. Organisations that have committed early are pulling ahead, compressing 
the window available to those still evaluating. The regulatory gap presents a 
dual risk: liability uncertainty for those already deployed, and a potential 
compliance cliff for those deploying once frameworks are finalised.

Market concentration is an emerging concern. As the sector matures, consolidation 
is likely, raising questions about vendor dependency and long-term flexibility 
for organisations that have not negotiated appropriately structured contracts.

---

## Critical Perspectives

The analysis above should be treated with appropriate caution. Key growth 
statistics originate from industry sources with a commercial interest in 
positive framing. Published case studies disproportionately represent 
successful implementations — failed deployments are rarely documented publicly.

Additionally, the report does not fully account for workforce resistance, 
the ethical dimensions of automated decision-making, or the significant 
variation in adoption rates across different geographies and sectors.

---

## Conclusions

{topic.title()} represents a genuine and significant shift, not a passing trend. 
However, organisations should approach deployment with clear-eyed realism about 
ROI timelines, regulatory exposure, and the limits of currently published evidence.

---

## Limitations

- This report is based on mock data generated for pipeline development purposes
- In production, all sections would reflect real web research and live analysis
- Statistics cited are illustrative placeholders, not verified figures
"""
        save_report(topic, report)
        return report

    # ---------------------------------------------------------------------------
    # Live Mode — real API call
    # ---------------------------------------------------------------------------

    print("[Writer] Live mode — contacting Claude API...")

    response = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=8096,
        system=WRITER_SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": f"""Topic: {topic}

--- RESEARCH ---
{research}

--- ANALYSIS ---
{analysis}

--- CRITIQUE ---
{critique}

Write the final report now."""
            }
        ]
    )

    print("[Writer] Report written.")
    report = response.content[0].text
    save_report(topic, report)
    return report


def save_report(topic: str, report: str) -> str:
    """
    Save the final report as a markdown file in the output/ folder.

    Filename is generated from the topic and current timestamp to avoid
    overwriting previous reports on the same topic.

    Args:
        topic (str): Used to generate a clean filename.
        report (str): The full markdown report text to save.

    Returns:
        str: The full file path of the saved report.
    """

    # Create output/ folder if it doesn't exist
    os.makedirs("output", exist_ok=True)

    # Generate a clean filename from the topic and timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    clean_topic = topic.lower().replace(" ", "_")[:40]
    filename = f"output/{clean_topic}_{timestamp}.md"

    with open(filename, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"[Writer] Report saved to: {filename}")
    return filename


# ---------------------------------------------------------------------------
# Direct execution — for testing this agent in isolation
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    mock_research = "AI in healthcare is growing. Market size $45bn. 67% adoption rate."
    mock_analysis = "Key insight: rapid adoption. Regulation lagging. ROI proven but patchy."
    mock_critique = "Growth stats unverified. ROI suffers survivorship bias. Misses workforce impact."

    result = run_writer(
        "artificial intelligence in healthcare 2025",
        mock_research,
        mock_analysis,
        mock_critique
    )
    print("\n--- REPORT OUTPUT ---")
    print(result)